//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.06 at 10:46:43 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://127.0.0.1:8080/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package _1._0._0._127._8080.webservice;
